

CREATE TABLE NODE
(
  ID 				INTEGER IDENTITY(1,1) NOT NULL,
  VERSION 			INTEGER NOT NULL,
  TYPE    			VARCHAR(100) NOT NULL,
  ISROOT			CHAR(1) DEFAULT 'N',
  VALID				CHAR(1) DEFAULT 'N',
  WAREHOUSE_SUBMIT	CHAR(1) DEFAULT 'N',
  PARENT_NODE_ID	INTEGER,
  USR_CREATED		VARCHAR(50),
  DATE_CREATED  	DATETIME,
  USR_UPDATED		VARCHAR(50),
  DATE_UPDATED  	DATETIME,
  DESCRIPTION		VARCHAR(255),
  PRIMARY KEY ( ID ),
  FOREIGN KEY (PARENT_NODE_ID) REFERENCES NODE(ID)
)

CREATE TABLE FIELD
(
  NAME     			VARCHAR(100) NOT NULL,
  VALUE    			VARCHAR(255),
  NODE_ID			INTEGER NOT NULL,
  FOREIGN KEY (NODE_ID) REFERENCES NODE(ID)
)

CREATE TRIGGER updateTrigger
ON NODE
FOR UPDATE
AS
BEGIN
	UPDATE N
	SET N.VERSION=N.VERSION+1,  
	N.DATE_UPDATED = CURRENT_TIMESTAMP
	FROM NODE N
	INNER JOIN inserted i
	ON N.ID = i.ID
END


CREATE TRIGGER createTrigger
ON NODE
FOR INSERT
AS
BEGIN
	UPDATE N
	SET N.DATE_CREATED = CURRENT_TIMESTAMP
	FROM NODE N
	INNER JOIN inserted i
	ON N.ID = i.ID
END

